ZR.UI/Models/ErrorViewModel.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/


namespace ZR.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ZR.UI/Controllers/AddressController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/

using ZR.Resources.Extensions;
using ZR.UI.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace ZR.UI.Controllers
{
    public class AddressController : BaseSiteController
    {
        private readonly ILogger<AddressController> _logger;

        public AddressController(ILogger<AddressController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

ZR.UI/Controllers/CompanyController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/


using ZR.Business.Security.Interfaces;
using ZR.Business.Services.Interfaces;
using ZR.Resources.Dtos;
using ZR.Resources.Extensions;
using ZR.UI.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ZR.UI.Controllers
{
    public class CompanyController : BaseSiteController
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly IRsaCryptograper _rsaCryptograper;

        public CompanyController(ILogger<CompanyController> logger, IRsaCryptograper rsaCryptograper)
        {
            _logger = logger;
            _rsaCryptograper = rsaCryptograper;
        }


        public async Task<IActionResult> Index()
        {
            List<CompanyDto> companyDtosList = new List<CompanyDto>();
            using (HttpClient? httpClient = new HttpClient())
            {
                //if have time put get the REST API URL From a Json file as well as the files
                string apiUrlAddress = "https://localhost:7135/api/CompanyApi/GetAll";
                using (HttpResponseMessage? response = await httpClient.GetAsync(apiUrlAddress))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    string enData = _rsaCryptograper.Decrypt(apiResponse.ToString());
                    companyDtosList = JsonConvert.DeserializeObject<List<CompanyDto>>(enData);
                }
            }
            return View(companyDtosList);
        }

        //public IActionResult Index()
        //{
        //    //var data =  _Service.Service<ICompanyService>().AsyncGetAll();

        //    return View();
        //}
    }
}

ZR.UI/Controllers/ContactController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/


using ZR.Resources.Extensions;
using ZR.UI.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace ZR.UI.Controllers
{
    public class ContactController : BaseSiteController
    {
        private readonly ILogger<ContactController> _logger;

        public ContactController(ILogger<ContactController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

ZR.UI/Controllers/HomeController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/


using ZR.Resources.Dtos;
using ZR.Resources.Extensions;
using ZR.UI.Extensions;
using ZR.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;

namespace ZR.UI.Controllers
{
    public class HomeController : BaseSiteController
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ZR.UI/Controllers/SettingController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/
using ZR.Resources.Extensions;
using ZR.UI.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace ZR.UI.Controllers
{
    public class SettingController : BaseSiteController
    {
        private readonly ILogger<SettingController> _logger;

        public SettingController(ILogger<SettingController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

ZR.UI/Controllers/TelephoneController.cs
/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/


using ZR.Resources.Extensions;
using ZR.UI.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace ZR.UI.Controllers
{
    public class TelephoneController : BaseSiteController
    {
        private readonly ILogger<TelephoneController> _logger;

        public TelephoneController(ILogger<TelephoneController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

ZR.UI/Views/Address/Index.cshtml
@*/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/
*@

@*@using ZR.Resources.Dtos;
@model System.Collections.Generic.IEnumerable<CompanyDto>*@

@{
    ViewData["Title"] = "Home Page";
}

<h3>ADDRESS</h3>
<!---FORM UI-->
    <form class="form">
      <label for="txtName">Name</label>
      <input type="text" id="txtName"/>

      <label for="txtMessage">Message</label>
      <textarea id="txtMessage"></textarea>

      <label for="ddlStatus">Status</label>
      <select id="ddlStatus">
          <option selected>--Please Select Status--</option>
        <option>Active</option>
        <option>In Active</option>
      </select>

      <input type="submit" value="Save"/>
    </form>

    <h1></h1>
     <table class="zebra-tbl">
    <thead>
        <tr>
            <th>ID</th>
            <th>Encrypt CompanyID</th>
            <th>Company Name</th>
            <th>Encrypt Company Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

         <tr>
                <td>CompanyId</td>
                <td>EncryptCompanyId</td>
                <td>CompanyName#</td>
                <td>EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="x">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="x" name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        @*@foreach (var item in Model)
        {
            <tr>
                <td>@item.CompanyId</td>
                <td>@item.EncryptCompanyId</td>
                <td>@item.CompanyName#</td>
                <td>@item.EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="@item.CompanyId name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        }*@
    </tbody>
</table>

ZR.UI/Views/Company/Index.cshtml
@*/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/
*@

@using ZR.Resources.Dtos;
@model System.Collections.Generic.IEnumerable<CompanyDto>

@{
    ViewData["Title"] = "Company";
}

<h3>Company</h3>
 
     

  
     <table class="zebra-tbl">
    <thead>
        <tr>
            <th>ID</th>
            <th>Encrypt CompanyID</th>
            <th>Company Name</th>
            <th>Encrypt Company Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

         <tr>
                <td>CompanyId</td>
                <td>Registrant Type</td>
                <td>Company Name </td>
                <td>Registration Number</td>
                <td>Tranding As</td>
                <td>Active</td>
                <td>Soft Deleted</td>
              
                <td>
                    Update
                </td>
                <td>
                    Delete
                </td>
                <td>
                    View Detials
                </td>
            </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.CompanyId</td>
                <td>@item.RegistrantType.ToString()</td>
                <td>@item.CompanyName</td>
                <td>@item.RegistrationNumber</td>
                <td>@item.TrandingAs</td>
                   <td>@item.IsActive</td>
                <td>@item.IsSoftDeleted</td>
                
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="@item.CompanyId name="CompanyId" />
                 
                    </form>
                </td>
                 <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>View Detials</button>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

ZR.UI/Views/Contact/Index.cshtml
@*/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/
*@

@*@using ZR.Resources.Dtos;
@model System.Collections.Generic.IEnumerable<CompanyDto>*@

@{
    ViewData["Title"] = "Home Page";
}
<h3>Contact</h3>
<!---FORM UI-->
    <form class="form">
      <label for="txtName">Name</label>
      <input type="text" id="txtName"/>

      <label for="txtMessage">Message</label>
      <textarea id="txtMessage"></textarea>

      <label for="ddlStatus">Status</label>
      <select id="ddlStatus">
          <option selected>--Please Select Status--</option>
        <option>Active</option>
        <option>In Active</option>
      </select>

      <input type="submit" value="Save"/>
    </form>

    <h1></h1>
     <table class="zebra-tbl">
    <thead>
        <tr>
            <th>ID</th>
            <th>Encrypt CompanyID</th>
            <th>Company Name</th>
            <th>Encrypt Company Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

         <tr>
                <td>CompanyId</td>
                <td>EncryptCompanyId</td>
                <td>CompanyName#</td>
                <td>EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="x">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="x" name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        @*@foreach (var item in Model)
        {
            <tr>
                <td>@item.CompanyId</td>
                <td>@item.EncryptCompanyId</td>
                <td>@item.CompanyName#</td>
                <td>@item.EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="@item.CompanyId name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        }*@
    </tbody>
</table>

ZR.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h3>Dashboard</h3>
<!---FORM UI-->
    <form class="form">
      <label for="txtName">Name</label>
      <input type="text" id="txtName"/>

      <label for="txtMessage">Message</label>
      <textarea id="txtMessage"></textarea>

      <label for="ddlStatus">Status</label>
      <select id="ddlStatus">
          <option selected>--Please Select Status--</option>
        <option>Active</option>
        <option>In Active</option>
      </select>

      <input type="submit" value="Save"/>
    </form>

    <h1></h1>
     <table class="zebra-tbl">
    <thead>
        <tr>
            <th>ID</th>
            <th>Encrypt CompanyID</th>
            <th>Company Name</th>
            <th>Encrypt Company Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

         <tr>
                <td>CompanyId</td>
                <td>EncryptCompanyId</td>
                <td>CompanyName#</td>
                <td>EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="x">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="x" name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        @*@foreach (var item in Model)
        {
            <tr>
                <td>@item.CompanyId</td>
                <td>@item.EncryptCompanyId</td>
                <td>@item.CompanyName#</td>
                <td>@item.EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="@item.CompanyId name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        }*@
    </tbody>
</table>

ZR.UI/Views/Setting/Index.cshtml
@*@using ZR.Resources.Dtos;
@model System.Collections.Generic.IEnumerable<CompanyDto>*@

@{
    ViewData["Title"] = "Home Page";
}
<h3>Settings</h3>
<!---FORM UI-->
    <form class="form">
      <label for="txtName">Name</label>
      <input type="text" id="txtName"/>

      <label for="txtMessage">Message</label>
      <textarea id="txtMessage"></textarea>

      <label for="ddlStatus">Status</label>
      <select id="ddlStatus">
          <option selected>--Please Select Status--</option>
        <option>Active</option>
        <option>In Active</option>
      </select>

      <input type="submit" value="Save"/>
    </form>

    <h1></h1>
     <table class="zebra-tbl">
    <thead>
        <tr>
            <th>ID</th>
            <th>Encrypt CompanyID</th>
            <th>Company Name</th>
            <th>Encrypt Company Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

         <tr>
                <td>CompanyId</td>
                <td>EncryptCompanyId</td>
                <td>CompanyName#</td>
                <td>EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="x">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="x" name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        @*@foreach (var item in Model)
        {
            <tr>
                <td>@item.CompanyId</td>
                <td>@item.EncryptCompanyId</td>
                <td>@item.CompanyName#</td>
                <td>@item.EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="@item.CompanyId name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        }*@
    </tbody>
</table>

ZR.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] IS Demo</title>
 
    <link rel="stylesheet" href="~/Styles/CSS/IS-App-Style.css" asp-append-version="true" />

      <link rel="apple-touch-icon" sizes="57x57" href="~/Styles/Icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/Styles/Icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/Styles/Icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/Styles/Icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/Styles/Icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/Styles/Icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/Styles/Icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/Styles/Icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/Styles/Icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/Styles/Icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Styles/Icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/Styles/Icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Styles/Icons/favicon-16x16.png">
    <link rel="manifest" href="~/Styles/Icons/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/Styles/Icons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    
</head>
<body>
    <header>

    </header>
    <div id="sidebar">  
        <div id="logo">
        <img src="/Images/logo.png"/>
        <i class="txt">Ziggy Rafiq</i>
      </div>

    
      <a class="current" asp-area="" asp-controller="Home" asp-action="Index">
                  <i class="ico">&#9733;</i>
             
        <i class="txt">Dashboard</i>
      </a>

      <a asp-area="" asp-controller="Company" asp-action="Index">
        <i class="ico">&#9728;</i>
        <i class="txt">Company</i>
      </a>
      <a asp-area="" asp-controller="Contact" asp-action="Index">
        <i class="ico">&#9737;</i>
        <i class="txt">Contact</i>
      </a>
     <a asp-area="" asp-controller="Address" asp-action="Index">
        <i class="ico">&#9737;</i>
        <i class="txt">Address</i>
      </a>
          <a asp-area="" asp-controller="Telephone" asp-action="Index">
        <i class="ico">&#9737;</i>
        <i class="txt">Telephone</i>
      </a>
          <a asp-area="" asp-controller="Setting" asp-action="Index">
        <i class="ico">&#9737;</i>
        <i class="txt">Setting</i>
      </a>
    </div>
   

    <main id="app-main" role="main">
          @RenderBody()
         
        </main>
  @*  <div class="container">
        <p>This is Ziggy Container</p>
    </div>
 *@
 
  
    <script src="~/Scripts/IS-App-Scripts.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZR.UI/Views/Telephone/Index.cshtml
@*/************************************************************************************************************
*  COPYRIGHT BY ZIGGY RAFIQ (ZAHEER RAFIQ)
*  LinkedIn Profile URL Address: https://www.linkedin.com/in/ziggyrafiq/ 
*
*  System   :  	ZR Demo Project 01 - Book Api
*  Date     :  	25/09/2022
*  Author   :  	Ziggy Rafiq (https://www.ziggyrafiq.com)
*  Notes    :  	
*  Reminder :	PLEASE DO NOT CHANGE OR REMOVE AUTHOR NAME.
*
************************************************************************************************************/
*@

@*@using ZR.Resources.Dtos;
@model System.Collections.Generic.IEnumerable<CompanyDto>*@

@{
    ViewData["Title"] = "Home Page";
}

<h3>Telephpone</h3>
<!---FORM UI-->
    <form class="form">
      <label for="txtName">Name</label>
      <input type="text" id="txtName"/>

      <label for="txtMessage">Message</label>
      <textarea id="txtMessage"></textarea>

      <label for="ddlStatus">Status</label>
      <select id="ddlStatus">
          <option selected>--Please Select Status--</option>
        <option>Active</option>
        <option>In Active</option>
      </select>

      <input type="submit" value="Save"/>
    </form>

    <h1></h1>
     <table class="zebra-tbl">
    <thead>
        <tr>
            <th>ID</th>
            <th>Encrypt CompanyID</th>
            <th>Company Name</th>
            <th>Encrypt Company Name</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>

         <tr>
                <td>CompanyId</td>
                <td>EncryptCompanyId</td>
                <td>CompanyName#</td>
                <td>EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="x">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="x" name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        @*@foreach (var item in Model)
        {
            <tr>
                <td>@item.CompanyId</td>
                <td>@item.EncryptCompanyId</td>
                <td>@item.CompanyName#</td>
                <td>@item.EncryptCompanyName</td>
                <td>
                    <a asp-action="UpdateCompany" asp-route-id="@item.CompanyId">
                       <button>Update</button>
                    </a>
                </td>
                <td>
                    <form asp-action="DeleteCompany" method="post">
                        <input type="hidden" value="@item.CompanyId name="CompanyId" />
                 
                    </form>
                </td>
            </tr>
        }*@
    </tbody>
</table>